"""Pack the ground tiles Tidewake draws into one small sheet and write src/data/tileIndex.ts.

Raw tiles come from the read-only Unity pack (Super Retro Collection). The pack has no seamless sand/desert/dirt/swamp
ground, so those are recoloured copies of its speckled grass tiles. Nothing in the asset master is modified.
Run: python tools/pack_tiles.py
"""
from collections import Counter
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ENV = Path("E:/Pixel Games Asset Master/Assets/Gif/Super_Retro_Collection/Resources/Environments")
TILE = 16
COLS = 8

# name -> (base colour, speckle colour)
PALETTES = {
    "sand": ((240, 214, 160), (222, 192, 134)),
    "desert": ((232, 176, 104), (208, 150, 82)),
    "dirt": ((150, 110, 78), (128, 92, 62)),
    "swamp": ((70, 104, 52), (52, 82, 40)),
}


def crop(sheet: Image.Image, col: int, row: int) -> Image.Image:
    return sheet.crop((col * TILE, row * TILE, (col + 1) * TILE, (row + 1) * TILE))


def recolor(tile: Image.Image, base_to, speck_to) -> Image.Image:
    """Swap the most common colour for base_to and every other opaque colour for speck_to."""
    px = tile.load()
    counts = Counter(px[x, y] for y in range(TILE) for x in range(TILE) if px[x, y][3] > 0)
    base = counts.most_common(1)[0][0]
    out = tile.copy()
    o = out.load()
    for y in range(TILE):
        for x in range(TILE):
            if px[x, y][3] == 0:
                continue
            o[x, y] = (*(base_to if px[x, y] == base else speck_to), 255)
    return out


def tint(tile: Image.Image, mul) -> Image.Image:
    out = tile.copy()
    o = out.load()
    for y in range(TILE):
        for x in range(TILE):
            r, g, b, a = o[x, y]
            o[x, y] = (int(r * mul[0]), int(g * mul[1]), int(b * mul[2]), a)
    return out


def build_tiles(main: Image.Image, legacy: Image.Image):
    flat_grass = crop(main, 18, 30)
    speck_sources = [crop(legacy, 8, 115), crop(legacy, 7, 114), crop(legacy, 8, 114)]
    tiles = [
        ("grass.0", flat_grass),
        ("grass.1", crop(legacy, 7, 114)),
        ("grass.2", crop(legacy, 8, 114)),
        ("grass.3", crop(legacy, 7, 115)),
        ("grass.4", crop(legacy, 8, 115)),
        ("water.shallow", crop(main, 11, 37)),
        ("water.deep", tint(crop(main, 11, 37), (0.62, 0.72, 0.9))),
        ("stone.0", crop(main, 2, 36)),
    ]
    for name, (base, speck) in PALETTES.items():
        tiles.append((f"{name}.0", recolor(flat_grass, base, speck)))
        for i, src in enumerate(speck_sources, start=1):
            tiles.append((f"{name}.{i}", recolor(src, base, speck)))
    # Tilled farm soil: darker brown, darker still when watered.
    tiles.append(("soil.dry", recolor(speck_sources[0], (112, 78, 54), (92, 62, 42))))
    tiles.append(("soil.wet", recolor(speck_sources[0], (78, 54, 40), (62, 42, 32))))
    return tiles


def main() -> None:
    main_sheet = Image.open(ENV / "original_atlas.png").convert("RGBA")
    legacy_sheet = Image.open(ENV / "legacy_atlas.png").convert("RGBA")
    tiles = build_tiles(main_sheet, legacy_sheet)
    rows = (len(tiles) + COLS - 1) // COLS
    out = Image.new("RGBA", (COLS * TILE, rows * TILE), (0, 0, 0, 0))
    lines = []
    for n, (name, img) in enumerate(tiles):
        out.paste(img, ((n % COLS) * TILE, (n // COLS) * TILE))
        lines.append(f"  '{name}': {n},")
    pack = ROOT / "public" / "assets" / "pack"
    pack.mkdir(parents=True, exist_ok=True)
    out.save(pack / "tiles.png", optimize=True)
    ts = [
        "// Generated by tools/pack_tiles.py - do not edit. Frame index of each ground tile in public/assets/pack/tiles.png.",
        "export const TILE_FRAMES = {",
        *lines,
        "} as const;",
        "export type TileName = keyof typeof TILE_FRAMES;",
        "",
    ]
    (ROOT / "src" / "data" / "tileIndex.ts").write_text("\n".join(ts), encoding="utf-8")
    print(f"packed {len(tiles)} tiles into {out.width}x{out.height}")


if __name__ == "__main__":
    main()
